### ISSUE TITLE
Ensure all table schema docs (in Confluence) are correct and up-to-date

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/data-models-ARCHIVED#14]
- [ ] [Grants](https://sagebionetworks.jira.com/wiki/spaces/PS/pages/823361798/CSBC+PSON+Grant+Schema)
- [ ] [Projects](https://sagebionetworks.jira.com/wiki/spaces/PS/pages/959447139/CSBC+PSON+Project+Schema)
- [ ] [Datasets](https://sagebionetworks.jira.com/wiki/spaces/PS/pages/823263736/CSBC+PSON+Dataset+Schema)
- [ ] [Publications](https://sagebionetworks.jira.com/wiki/spaces/PS/pages/823165282/CSBC+PSON+Publications+Schema)
- [ ] [Tools](https://sagebionetworks.jira.com/wiki/spaces/PS/pages/828538899/CSBC+PSON+Tools+Schema)
- [ ] [Datafiles](https://sagebionetworks.jira.com/wiki/spaces/PS/pages/957775911/CSBC+PSON+Data+File+Schema)

**Comment by jaeddy** [comment]
Check with Platform if anyone is still using these docs. @milen-sage can think about whether auto-generation of schemas might be in scope for FAIR Data.

**Comment by vpchung** [comment]
@mc2-center/triage-team since this is related to documentation, is this something I should update or you/Amber?

**Comment by aclayton555** [comment]
It looks like some of these are still being maintained for other portals, but let's ask Milen if FAIR is inclined to have these maintained. For example, I don't see NF or HTAN schemas on here.
I feel like trying to keep these updated would be rather time consuming, and may fall out of sync with the latest version of a data model. I know schematic allows you to export any manifest directly from a data model, so I'm inclined to approach that as the source of truth.
In general, I don't know the original intent of these pages, but updating these for CSBC at this point might not be trivial.

**Comment by vpchung** [comment]
@aclayton555 thanks!  I will go ahead and move this over to our [data-models repo](https://github.com/mc2-center/data-models) then, as I think it's most relevant there.

**Comment by aclayton555** [comment]
I had previously put a ticket for this in our backlog. If this issue is closed, please close out: https://sagebionetworks.jira.com/browse/CPO-79

**Comment by aclayton555** [comment]
Discussed with Milen on 2022.11.21 FAIR/MC2 Stakeholder call: 

- Might be more relevant for schematic-db in the context of developing portal tables
- Milen to create a new issue that points to confluence doc and plan to revisit this in the context of schematic-db. Will chat more with Andrew
- MC2 can close this for now. When this work is pursued, it will be project agnostic. Any MC2-specific work will be tracked accordingly
